### ISSUE TITLE
ImportError: cannot import name '_TYPE_SOCKS_OPTIONS' from 'urllib3.contrib.socks'

### ISSUE THREAD

**Issue by daniel-ac-martin** [mansuf/requests-doh#5]
### Subject

When I try to import `DNSOverHTTPSSession`, I receive the following error:

```
ImportError: cannot import name '_TYPE_SOCKS_OPTIONS' from 'urllib3.contrib.socks' (/usr/lib/python3.12/site-packages/urllib3/contrib/socks.py)
```

### Environment

OS Linux-6.7.5-200.fc39.x86_64-x86_64-with-glibc2.38
Python 3.12.2
OpenSSL 3.1.1 30 May 2023
urllib3 1.26.18

requests_doh, installed from pip. (`pip install requests_doh -U`) (v0.3.3?)

### Steps to Reproduce

```py
from requests_doh import DNSOverHTTPSSession
```

### Expected Behaviour

`DNSOverHTTPSSession` should be imported without error.

### Actual Behaviour

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[90], line 1
----> 1 from requests_doh import DNSOverHTTPSSession

File ~/.local/lib/python3.12/site-packages/requests_doh/__init__.py:12
      9 __license__ = "MIT"
     10 __repository__ = "mansuf/requests-doh"
---> 12 from .session import *
     13 from .adapter import *
     14 from .resolver import *

File ~/.local/lib/python3.12/site-packages/requests_doh/session.py:2
      1 import requests
----> 2 from .adapter import DNSOverHTTPSAdapter
      4 __all__ = ('DNSOverHTTPSSession',)
      6 class DNSOverHTTPSSession(requests.Session):

File ~/.local/lib/python3.12/site-packages/requests_doh/adapter.py:15
      8 from .connector.default import (
      9     DoHHTTPConnection,
     10     DoHHTTPSConnection,
     11 )
     13 from .cachemanager import set_dns_cache_expire_time
---> 15 from .connector.proxies import (
     16     SOCKSConnection,
     17     SOCKSHTTPSConnection
     18 )
     20 from .resolver import set_dns_provider
     22 __all__ = ('DNSOverHTTPSAdapter',)  

File ~/.local/lib/python3.12/site-packages/requests_doh/connector/proxies.py:12
     10 import socket
     11 import struct
---> 12 from urllib3.contrib.socks import socks, _TYPE_SOCKS_OPTIONS, SocketTimeout
     13 from urllib3.exceptions import ConnectTimeoutError, NewConnectionError
     14 from urllib3.connection import HTTPConnection, HTTPSConnection

ImportError: cannot import name '_TYPE_SOCKS_OPTIONS' from 'urllib3.contrib.socks' (/usr/lib/python3.12/site-packages/urllib3/contrib/socks.py)
```

I'm still quite new to Python, so please accept my apologies if I've done something daft.

**Comment by mansuf** [comment]
Your urllib3 version is outdated, try installing version 2.x. I have tried install the exact same version as yours and indeed it trigger the same errors.

```
(requests-doh-issue-5) D:\Yo WTF IS THIS\python venv\requests-doh-issue-5\Scripts>pip freeze | findstr urllib3
urllib3==1.26.18

(requests-doh-issue-5) D:\Yo WTF IS THIS\python venv\requests-doh-issue-5\Scripts>python -c "from requests_doh import DNSOverHTTPSSession"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Yo WTF IS THIS\python venv\requests-doh-issue-5\Lib\site-packages\requests_doh\__init__.py", line 12, in <module>
    from .session import *
  File "D:\Yo WTF IS THIS\python venv\requests-doh-issue-5\Lib\site-packages\requests_doh\session.py", line 2, in <module>
    from .adapter import DNSOverHTTPSAdapter
  File "D:\Yo WTF IS THIS\python venv\requests-doh-issue-5\Lib\site-packages\requests_doh\adapter.py", line 15, in <module>
    from .connector.proxies import (
  File "D:\Yo WTF IS THIS\python venv\requests-doh-issue-5\Lib\site-packages\requests_doh\connector\proxies.py", line 12, in <module>
    from urllib3.contrib.socks import socks, _TYPE_SOCKS_OPTIONS, SocketTimeout
ImportError: cannot import name '_TYPE_SOCKS_OPTIONS' from 'urllib3.contrib.socks' (D:\Yo WTF IS THIS\python venv\requests-doh-issue-5\Lib\site-packages\urllib3\contrib\socks.py)
```

**Comment by daniel-ac-martin** [comment]
Thanks @mansuf. Sorry for bothering you with something so trivial.

I actually had v2 installed but my python set-up was preferring an old, system-wide package.

For any other Python newbies who come across this issue, I solved it by setting up a `PYTHONPATH` environment variable, so that my locally installed packages would be searched before the system-wide ones. As I'm on a GNU/Linux system (Fedora), I added the following line to be `.bashrc`:
```bash
export PYTHONPATH="${HOME}/.local/lib/python3.12/site-packages:${PYTHONPATH}"
```

**Comment by mansuf** [comment]
No problem, i'm glad the problem has been solved 👍.

> For any other Python newbies who come across this issue, I solved it by setting up a PYTHONPATH environment variable, so that my locally installed packages would be searched before the system-wide ones. As I'm on a GNU/Linux system (Fedora), I added the following line to be .bashrc:

Thank you for giving solution for GNU/Linux users, i will pin this issue for everyone to see it.
